// src/views/cms/renderer/templateRenderer/inputRenderer.vue
<template>
    <a-input
        :placeholder="element.props.placeholder"
        :defaultValue="element.props.defaultValue"
        :style="element.css"
    ></a-input>
</template>

<style lang="less">
.template-root-renderer {
    position: relative;
}
</style>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
import { IPageJSONConfig } from "@/interface/cmsComponents";
import { PropType } from "vue";
@Component<TemplateInputRenderer>({
    name: "template-input-renderer",
    props: {
        element: {
            type: Object as PropType<IPageJSONConfig>,
            required: true,
        },
    },
})
export default class TemplateInputRenderer extends Vue {
    @Prop() public element?: IPageJSONConfig;
}
</script>

// src/views/cms/renderer/dynamicRenderer/inputRenderer.tsx
import { componentRenderFunc } from "@/interface/renderer";
import { IInputProps } from "@/interface/cmsComponents/input";

const render: componentRenderFunc = function (h, element) {
    const props = (element.props || {}) as IInputProps;
    const defaultProps: IInputProps = {
        placeholder: props.placeholder || "",
        defaultValue: props.defaultValue || "",
    };
    return (
        <a-input
            placeholder={defaultProps.placeholder}
            defaultValue={defaultProps.defaultValue}
            style={element.css}
        ></a-input>
    );
};

export default render;
